// Copyright (C) 2026 Polytope Labs.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Scalar filter input type registration.
//!
//! [`register_scalar_filters`] registers the shared filter input types that
//! apply to every scalar GraphQL type (e.g. `StringFilter`, `IntFilter`,
//! `BooleanFilter`).  These types are registered once and referenced by every
//! per-entity `{Entity}Filter` input object generated by the schema builder.

use async_graphql::dynamic::*;

/// Register all scalar filter input types (StringFilter, IntFilter, etc.)
/// into the schema builder.
///
/// These are shared across all entity types.
pub fn register_scalar_filters(builder: SchemaBuilder) -> SchemaBuilder {
	builder
		.register(string_filter())
		.register(int_filter())
		.register(bigint_filter())
		.register(float_filter())
		.register(bigfloat_filter())
		.register(boolean_filter())
		.register(date_filter())
		.register(datetime_filter())
		.register(json_filter())
		// PostGraphile-compatible dedicated scalars and filters
		.register(Scalar::new("UUID"))
		.register(Scalar::new("Time"))
		.register(Scalar::new("BitString"))
		.register(Scalar::new("InternetAddress"))
		.register(interval_type())
		.register(interval_input())
		.register(point_type())
		.register(point_input())
		.register(uuid_filter())
		.register(time_filter())
		.register(bitstring_filter())
		.register(internet_address_filter())
		.register(interval_filter())
		// List filter types for array columns
		.register(string_list_filter())
		.register(int_list_filter())
		.register(bigint_list_filter())
		.register(float_list_filter())
		.register(bigfloat_list_filter())
		.register(boolean_list_filter())
		.register(date_list_filter())
		.register(datetime_list_filter())
		.register(json_list_filter())
		.register(uuid_list_filter())
		.register(time_list_filter())
		.register(internet_address_list_filter())
}

fn string_filter() -> InputObject {
	InputObject::new("StringFilter")
		.field(InputValue::new("isNull", TypeRef::named(TypeRef::BOOLEAN)))
		.field(InputValue::new("equalTo", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("notEqualTo", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("distinctFrom", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("notDistinctFrom", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("in", TypeRef::named_nn_list(TypeRef::STRING)))
		.field(InputValue::new("notIn", TypeRef::named_nn_list(TypeRef::STRING)))
		.field(InputValue::new("lessThan", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("lessThanOrEqualTo", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("greaterThan", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("greaterThanOrEqualTo", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("includes", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("notIncludes", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("includesInsensitive", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("notIncludesInsensitive", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("startsWith", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("notStartsWith", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("startsWithInsensitive", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("notStartsWithInsensitive", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("endsWith", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("notEndsWith", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("endsWithInsensitive", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("notEndsWithInsensitive", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("like", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("notLike", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("likeInsensitive", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("notLikeInsensitive", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("equalToInsensitive", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("notEqualToInsensitive", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("distinctFromInsensitive", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("notDistinctFromInsensitive", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("inInsensitive", TypeRef::named_nn_list(TypeRef::STRING)))
		.field(InputValue::new("notInInsensitive", TypeRef::named_nn_list(TypeRef::STRING)))
		.field(InputValue::new("lessThanInsensitive", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("lessThanOrEqualToInsensitive", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("greaterThanInsensitive", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("greaterThanOrEqualToInsensitive", TypeRef::named(TypeRef::STRING)))
}

fn int_filter() -> InputObject {
	InputObject::new("IntFilter")
		.field(InputValue::new("equalTo", TypeRef::named(TypeRef::INT)))
		.field(InputValue::new("notEqualTo", TypeRef::named(TypeRef::INT)))
		.field(InputValue::new("isNull", TypeRef::named(TypeRef::BOOLEAN)))
		.field(InputValue::new("in", TypeRef::named_nn_list(TypeRef::INT)))
		.field(InputValue::new("notIn", TypeRef::named_nn_list(TypeRef::INT)))
		.field(InputValue::new("lessThan", TypeRef::named(TypeRef::INT)))
		.field(InputValue::new("lessThanOrEqualTo", TypeRef::named(TypeRef::INT)))
		.field(InputValue::new("greaterThan", TypeRef::named(TypeRef::INT)))
		.field(InputValue::new("greaterThanOrEqualTo", TypeRef::named(TypeRef::INT)))
		.field(InputValue::new("distinctFrom", TypeRef::named(TypeRef::INT)))
		.field(InputValue::new("notDistinctFrom", TypeRef::named(TypeRef::INT)))
}

fn bigint_filter() -> InputObject {
	InputObject::new("BigIntFilter")
		.field(InputValue::new("equalTo", TypeRef::named("BigInt")))
		.field(InputValue::new("notEqualTo", TypeRef::named("BigInt")))
		.field(InputValue::new("isNull", TypeRef::named(TypeRef::BOOLEAN)))
		.field(InputValue::new("in", TypeRef::named_nn_list("BigInt")))
		.field(InputValue::new("notIn", TypeRef::named_nn_list("BigInt")))
		.field(InputValue::new("lessThan", TypeRef::named("BigInt")))
		.field(InputValue::new("lessThanOrEqualTo", TypeRef::named("BigInt")))
		.field(InputValue::new("greaterThan", TypeRef::named("BigInt")))
		.field(InputValue::new("greaterThanOrEqualTo", TypeRef::named("BigInt")))
		.field(InputValue::new("distinctFrom", TypeRef::named("BigInt")))
		.field(InputValue::new("notDistinctFrom", TypeRef::named("BigInt")))
}

fn float_filter() -> InputObject {
	InputObject::new("FloatFilter")
		.field(InputValue::new("equalTo", TypeRef::named(TypeRef::FLOAT)))
		.field(InputValue::new("notEqualTo", TypeRef::named(TypeRef::FLOAT)))
		.field(InputValue::new("isNull", TypeRef::named(TypeRef::BOOLEAN)))
		.field(InputValue::new("in", TypeRef::named_nn_list(TypeRef::FLOAT)))
		.field(InputValue::new("notIn", TypeRef::named_nn_list(TypeRef::FLOAT)))
		.field(InputValue::new("lessThan", TypeRef::named(TypeRef::FLOAT)))
		.field(InputValue::new("lessThanOrEqualTo", TypeRef::named(TypeRef::FLOAT)))
		.field(InputValue::new("greaterThan", TypeRef::named(TypeRef::FLOAT)))
		.field(InputValue::new("greaterThanOrEqualTo", TypeRef::named(TypeRef::FLOAT)))
		.field(InputValue::new("distinctFrom", TypeRef::named(TypeRef::FLOAT)))
		.field(InputValue::new("notDistinctFrom", TypeRef::named(TypeRef::FLOAT)))
}

fn bigfloat_filter() -> InputObject {
	InputObject::new("BigFloatFilter")
		.field(InputValue::new("equalTo", TypeRef::named("BigFloat")))
		.field(InputValue::new("notEqualTo", TypeRef::named("BigFloat")))
		.field(InputValue::new("isNull", TypeRef::named(TypeRef::BOOLEAN)))
		.field(InputValue::new("in", TypeRef::named_nn_list("BigFloat")))
		.field(InputValue::new("notIn", TypeRef::named_nn_list("BigFloat")))
		.field(InputValue::new("lessThan", TypeRef::named("BigFloat")))
		.field(InputValue::new("lessThanOrEqualTo", TypeRef::named("BigFloat")))
		.field(InputValue::new("greaterThan", TypeRef::named("BigFloat")))
		.field(InputValue::new("greaterThanOrEqualTo", TypeRef::named("BigFloat")))
		.field(InputValue::new("distinctFrom", TypeRef::named("BigFloat")))
		.field(InputValue::new("notDistinctFrom", TypeRef::named("BigFloat")))
}

fn boolean_filter() -> InputObject {
	InputObject::new("BooleanFilter")
		.field(InputValue::new("equalTo", TypeRef::named(TypeRef::BOOLEAN)))
		.field(InputValue::new("notEqualTo", TypeRef::named(TypeRef::BOOLEAN)))
		.field(InputValue::new("isNull", TypeRef::named(TypeRef::BOOLEAN)))
		.field(InputValue::new("distinctFrom", TypeRef::named(TypeRef::BOOLEAN)))
		.field(InputValue::new("notDistinctFrom", TypeRef::named(TypeRef::BOOLEAN)))
}

fn date_filter() -> InputObject {
	InputObject::new("DateFilter")
		.field(InputValue::new("equalTo", TypeRef::named("Date")))
		.field(InputValue::new("notEqualTo", TypeRef::named("Date")))
		.field(InputValue::new("isNull", TypeRef::named(TypeRef::BOOLEAN)))
		.field(InputValue::new("in", TypeRef::named_nn_list("Date")))
		.field(InputValue::new("notIn", TypeRef::named_nn_list("Date")))
		.field(InputValue::new("lessThan", TypeRef::named("Date")))
		.field(InputValue::new("lessThanOrEqualTo", TypeRef::named("Date")))
		.field(InputValue::new("greaterThan", TypeRef::named("Date")))
		.field(InputValue::new("greaterThanOrEqualTo", TypeRef::named("Date")))
		.field(InputValue::new("distinctFrom", TypeRef::named("Date")))
		.field(InputValue::new("notDistinctFrom", TypeRef::named("Date")))
}

fn datetime_filter() -> InputObject {
	InputObject::new("DatetimeFilter")
		.field(InputValue::new("equalTo", TypeRef::named("Datetime")))
		.field(InputValue::new("notEqualTo", TypeRef::named("Datetime")))
		.field(InputValue::new("isNull", TypeRef::named(TypeRef::BOOLEAN)))
		.field(InputValue::new("in", TypeRef::named_nn_list("Datetime")))
		.field(InputValue::new("notIn", TypeRef::named_nn_list("Datetime")))
		.field(InputValue::new("lessThan", TypeRef::named("Datetime")))
		.field(InputValue::new("lessThanOrEqualTo", TypeRef::named("Datetime")))
		.field(InputValue::new("greaterThan", TypeRef::named("Datetime")))
		.field(InputValue::new("greaterThanOrEqualTo", TypeRef::named("Datetime")))
		.field(InputValue::new("distinctFrom", TypeRef::named("Datetime")))
		.field(InputValue::new("notDistinctFrom", TypeRef::named("Datetime")))
}

fn json_filter() -> InputObject {
	InputObject::new("JSONFilter")
		.field(InputValue::new("equalTo", TypeRef::named("JSON")))
		.field(InputValue::new("notEqualTo", TypeRef::named("JSON")))
		.field(InputValue::new("isNull", TypeRef::named(TypeRef::BOOLEAN)))
		.field(InputValue::new("distinctFrom", TypeRef::named("JSON")))
		.field(InputValue::new("notDistinctFrom", TypeRef::named("JSON")))
}

// ── PostGraphile-compatible object types ────────────────────────────────────

fn object_field_resolver(
	field_name: &'static str,
) -> impl Fn(ResolverContext) -> FieldFuture + Send + Sync {
	move |ctx| {
		let val = ctx.parent_value.as_value().and_then(|v| match v {
			async_graphql::Value::Object(map) => map.get(field_name).cloned(),
			_ => None,
		});
		FieldFuture::new(async move { Ok(val.map(FieldValue::value)) })
	}
}

fn interval_type() -> Object {
	Object::new("Interval")
		.field(Field::new(
			"seconds",
			TypeRef::named(TypeRef::INT),
			object_field_resolver("seconds"),
		))
		.field(Field::new(
			"minutes",
			TypeRef::named(TypeRef::INT),
			object_field_resolver("minutes"),
		))
		.field(Field::new("hours", TypeRef::named(TypeRef::INT), object_field_resolver("hours")))
		.field(Field::new("days", TypeRef::named(TypeRef::INT), object_field_resolver("days")))
		.field(Field::new("months", TypeRef::named(TypeRef::INT), object_field_resolver("months")))
		.field(Field::new("years", TypeRef::named(TypeRef::INT), object_field_resolver("years")))
}

fn interval_input() -> InputObject {
	InputObject::new("IntervalInput")
		.field(InputValue::new("seconds", TypeRef::named(TypeRef::INT)))
		.field(InputValue::new("minutes", TypeRef::named(TypeRef::INT)))
		.field(InputValue::new("hours", TypeRef::named(TypeRef::INT)))
		.field(InputValue::new("days", TypeRef::named(TypeRef::INT)))
		.field(InputValue::new("months", TypeRef::named(TypeRef::INT)))
		.field(InputValue::new("years", TypeRef::named(TypeRef::INT)))
}

fn point_type() -> Object {
	Object::new("Point")
		.field(Field::new("x", TypeRef::named(TypeRef::FLOAT), object_field_resolver("x")))
		.field(Field::new("y", TypeRef::named(TypeRef::FLOAT), object_field_resolver("y")))
}

fn point_input() -> InputObject {
	InputObject::new("PointInput")
		.field(InputValue::new("x", TypeRef::named_nn(TypeRef::FLOAT)))
		.field(InputValue::new("y", TypeRef::named_nn(TypeRef::FLOAT)))
}

// ── Dedicated scalar filter types ───────────────────────────────────────────

fn comparable_filter(name: &str, scalar: &str) -> InputObject {
	InputObject::new(name)
		.field(InputValue::new("equalTo", TypeRef::named(scalar)))
		.field(InputValue::new("notEqualTo", TypeRef::named(scalar)))
		.field(InputValue::new("isNull", TypeRef::named(TypeRef::BOOLEAN)))
		.field(InputValue::new("in", TypeRef::named_nn_list(scalar)))
		.field(InputValue::new("notIn", TypeRef::named_nn_list(scalar)))
		.field(InputValue::new("lessThan", TypeRef::named(scalar)))
		.field(InputValue::new("lessThanOrEqualTo", TypeRef::named(scalar)))
		.field(InputValue::new("greaterThan", TypeRef::named(scalar)))
		.field(InputValue::new("greaterThanOrEqualTo", TypeRef::named(scalar)))
		.field(InputValue::new("distinctFrom", TypeRef::named(scalar)))
		.field(InputValue::new("notDistinctFrom", TypeRef::named(scalar)))
}

fn equality_filter(name: &str, scalar: &str) -> InputObject {
	InputObject::new(name)
		.field(InputValue::new("equalTo", TypeRef::named(scalar)))
		.field(InputValue::new("notEqualTo", TypeRef::named(scalar)))
		.field(InputValue::new("isNull", TypeRef::named(TypeRef::BOOLEAN)))
		.field(InputValue::new("distinctFrom", TypeRef::named(scalar)))
		.field(InputValue::new("notDistinctFrom", TypeRef::named(scalar)))
}

fn uuid_filter() -> InputObject {
	comparable_filter("UUIDFilter", "UUID")
}

fn time_filter() -> InputObject {
	comparable_filter("TimeFilter", "Time")
}

fn bitstring_filter() -> InputObject {
	comparable_filter("BitStringFilter", "BitString")
}

fn internet_address_filter() -> InputObject {
	comparable_filter("InternetAddressFilter", "InternetAddress")
}

fn interval_filter() -> InputObject {
	equality_filter("IntervalFilter", "IntervalInput")
}

// ── List filter types (for array columns) ───────────────────────────────────

fn list_filter(name: &str, scalar: &str) -> InputObject {
	InputObject::new(name)
		.field(InputValue::new("every", TypeRef::named(scalar)))
		.field(InputValue::new("some", TypeRef::named(scalar)))
		.field(InputValue::new("none", TypeRef::named(scalar)))
		.field(InputValue::new("isEmpty", TypeRef::named(TypeRef::BOOLEAN)))
}

fn string_list_filter() -> InputObject {
	list_filter("StringListFilter", "StringFilter")
}
fn int_list_filter() -> InputObject {
	list_filter("IntListFilter", "IntFilter")
}
fn bigint_list_filter() -> InputObject {
	list_filter("BigIntListFilter", "BigIntFilter")
}
fn float_list_filter() -> InputObject {
	list_filter("FloatListFilter", "FloatFilter")
}
fn bigfloat_list_filter() -> InputObject {
	list_filter("BigFloatListFilter", "BigFloatFilter")
}
fn boolean_list_filter() -> InputObject {
	list_filter("BooleanListFilter", "BooleanFilter")
}
fn date_list_filter() -> InputObject {
	list_filter("DateListFilter", "DateFilter")
}
fn datetime_list_filter() -> InputObject {
	list_filter("DatetimeListFilter", "DatetimeFilter")
}
fn json_list_filter() -> InputObject {
	list_filter("JSONListFilter", "JSONFilter")
}
fn uuid_list_filter() -> InputObject {
	list_filter("UUIDListFilter", "UUIDFilter")
}
fn time_list_filter() -> InputObject {
	list_filter("TimeListFilter", "TimeFilter")
}
fn internet_address_list_filter() -> InputObject {
	list_filter("InternetAddressListFilter", "InternetAddressFilter")
}

/// Return the name of the scalar filter type for a given GraphQL type name.
pub fn filter_type_for(graphql_type: &str) -> &'static str {
	match graphql_type {
		"String" => "StringFilter",
		"Int" => "IntFilter",
		"BigInt" => "BigIntFilter",
		"Float" => "FloatFilter",
		"BigFloat" => "BigFloatFilter",
		"Boolean" => "BooleanFilter",
		"Date" => "DateFilter",
		"Datetime" => "DatetimeFilter",
		"JSON" => "JSONFilter",
		"UUID" => "UUIDFilter",
		"Time" => "TimeFilter",
		"BitString" => "BitStringFilter",
		"InternetAddress" => "InternetAddressFilter",
		"Interval" => "IntervalFilter",
		_ => "StringFilter", // fallback
	}
}

/// Return the name of the list filter type for an array column whose elements
/// map to the given GraphQL type name.
pub fn list_filter_type_for(element_gql_type: &str) -> &'static str {
	match element_gql_type {
		"String" => "StringListFilter",
		"Int" => "IntListFilter",
		"BigInt" => "BigIntListFilter",
		"Float" => "FloatListFilter",
		"BigFloat" => "BigFloatListFilter",
		"Boolean" => "BooleanListFilter",
		"Date" => "DateListFilter",
		"Datetime" => "DatetimeListFilter",
		"JSON" => "JSONListFilter",
		"UUID" => "UUIDListFilter",
		"Time" => "TimeListFilter",
		"InternetAddress" => "InternetAddressListFilter",
		_ => "JSONListFilter", // fallback for unmapped array types
	}
}
