// Copyright (C) 2026 Polytope Labs.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// 	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Scalar filter input type registration.
//!
//! [`register_scalar_filters`] registers the shared filter input types that
//! apply to every scalar GraphQL type (e.g. `StringFilter`, `IntFilter`,
//! `BooleanFilter`).  These types are registered once and referenced by every
//! per-entity `{Entity}Filter` input object generated by the schema builder.

use async_graphql::dynamic::*;

/// Register all scalar filter input types (StringFilter, IntFilter, etc.)
/// into the schema builder.
///
/// These are shared across all entity types.
pub fn register_scalar_filters(builder: SchemaBuilder) -> SchemaBuilder {
	builder
		.register(string_filter())
		.register(int_filter())
		.register(bigint_filter())
		.register(float_filter())
		.register(bigfloat_filter())
		.register(boolean_filter())
		.register(date_filter())
		.register(datetime_filter())
		.register(json_filter())
}

fn string_filter() -> InputObject {
	InputObject::new("StringFilter")
		.field(InputValue::new("isNull", TypeRef::named(TypeRef::BOOLEAN)))
		.field(InputValue::new("equalTo", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("notEqualTo", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("distinctFrom", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("notDistinctFrom", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("in", TypeRef::named_nn_list(TypeRef::STRING)))
		.field(InputValue::new("notIn", TypeRef::named_nn_list(TypeRef::STRING)))
		.field(InputValue::new("lessThan", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("lessThanOrEqualTo", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("greaterThan", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("greaterThanOrEqualTo", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("includes", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("notIncludes", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("includesInsensitive", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("notIncludesInsensitive", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("startsWith", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("notStartsWith", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("startsWithInsensitive", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("notStartsWithInsensitive", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("endsWith", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("notEndsWith", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("endsWithInsensitive", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("notEndsWithInsensitive", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("like", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("notLike", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("likeInsensitive", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("notLikeInsensitive", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("equalToInsensitive", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("notEqualToInsensitive", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("distinctFromInsensitive", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("notDistinctFromInsensitive", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("inInsensitive", TypeRef::named_nn_list(TypeRef::STRING)))
		.field(InputValue::new("notInInsensitive", TypeRef::named_nn_list(TypeRef::STRING)))
		.field(InputValue::new("lessThanInsensitive", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("lessThanOrEqualToInsensitive", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("greaterThanInsensitive", TypeRef::named(TypeRef::STRING)))
		.field(InputValue::new("greaterThanOrEqualToInsensitive", TypeRef::named(TypeRef::STRING)))
}

fn int_filter() -> InputObject {
	InputObject::new("IntFilter")
		.field(InputValue::new("equalTo", TypeRef::named(TypeRef::INT)))
		.field(InputValue::new("notEqualTo", TypeRef::named(TypeRef::INT)))
		.field(InputValue::new("isNull", TypeRef::named(TypeRef::BOOLEAN)))
		.field(InputValue::new("in", TypeRef::named_nn_list(TypeRef::INT)))
		.field(InputValue::new("notIn", TypeRef::named_nn_list(TypeRef::INT)))
		.field(InputValue::new("lessThan", TypeRef::named(TypeRef::INT)))
		.field(InputValue::new("lessThanOrEqualTo", TypeRef::named(TypeRef::INT)))
		.field(InputValue::new("greaterThan", TypeRef::named(TypeRef::INT)))
		.field(InputValue::new("greaterThanOrEqualTo", TypeRef::named(TypeRef::INT)))
		.field(InputValue::new("distinctFrom", TypeRef::named(TypeRef::INT)))
		.field(InputValue::new("notDistinctFrom", TypeRef::named(TypeRef::INT)))
}

fn bigint_filter() -> InputObject {
	InputObject::new("BigIntFilter")
		.field(InputValue::new("equalTo", TypeRef::named("BigInt")))
		.field(InputValue::new("notEqualTo", TypeRef::named("BigInt")))
		.field(InputValue::new("isNull", TypeRef::named(TypeRef::BOOLEAN)))
		.field(InputValue::new("in", TypeRef::named_nn_list("BigInt")))
		.field(InputValue::new("notIn", TypeRef::named_nn_list("BigInt")))
		.field(InputValue::new("lessThan", TypeRef::named("BigInt")))
		.field(InputValue::new("lessThanOrEqualTo", TypeRef::named("BigInt")))
		.field(InputValue::new("greaterThan", TypeRef::named("BigInt")))
		.field(InputValue::new("greaterThanOrEqualTo", TypeRef::named("BigInt")))
		.field(InputValue::new("distinctFrom", TypeRef::named("BigInt")))
		.field(InputValue::new("notDistinctFrom", TypeRef::named("BigInt")))
}

fn float_filter() -> InputObject {
	InputObject::new("FloatFilter")
		.field(InputValue::new("equalTo", TypeRef::named(TypeRef::FLOAT)))
		.field(InputValue::new("notEqualTo", TypeRef::named(TypeRef::FLOAT)))
		.field(InputValue::new("isNull", TypeRef::named(TypeRef::BOOLEAN)))
		.field(InputValue::new("in", TypeRef::named_nn_list(TypeRef::FLOAT)))
		.field(InputValue::new("notIn", TypeRef::named_nn_list(TypeRef::FLOAT)))
		.field(InputValue::new("lessThan", TypeRef::named(TypeRef::FLOAT)))
		.field(InputValue::new("lessThanOrEqualTo", TypeRef::named(TypeRef::FLOAT)))
		.field(InputValue::new("greaterThan", TypeRef::named(TypeRef::FLOAT)))
		.field(InputValue::new("greaterThanOrEqualTo", TypeRef::named(TypeRef::FLOAT)))
		.field(InputValue::new("distinctFrom", TypeRef::named(TypeRef::FLOAT)))
		.field(InputValue::new("notDistinctFrom", TypeRef::named(TypeRef::FLOAT)))
}

fn bigfloat_filter() -> InputObject {
	InputObject::new("BigFloatFilter")
		.field(InputValue::new("equalTo", TypeRef::named("BigFloat")))
		.field(InputValue::new("notEqualTo", TypeRef::named("BigFloat")))
		.field(InputValue::new("isNull", TypeRef::named(TypeRef::BOOLEAN)))
		.field(InputValue::new("in", TypeRef::named_nn_list("BigFloat")))
		.field(InputValue::new("notIn", TypeRef::named_nn_list("BigFloat")))
		.field(InputValue::new("lessThan", TypeRef::named("BigFloat")))
		.field(InputValue::new("lessThanOrEqualTo", TypeRef::named("BigFloat")))
		.field(InputValue::new("greaterThan", TypeRef::named("BigFloat")))
		.field(InputValue::new("greaterThanOrEqualTo", TypeRef::named("BigFloat")))
		.field(InputValue::new("distinctFrom", TypeRef::named("BigFloat")))
		.field(InputValue::new("notDistinctFrom", TypeRef::named("BigFloat")))
}

fn boolean_filter() -> InputObject {
	InputObject::new("BooleanFilter")
		.field(InputValue::new("equalTo", TypeRef::named(TypeRef::BOOLEAN)))
		.field(InputValue::new("notEqualTo", TypeRef::named(TypeRef::BOOLEAN)))
		.field(InputValue::new("isNull", TypeRef::named(TypeRef::BOOLEAN)))
		.field(InputValue::new("distinctFrom", TypeRef::named(TypeRef::BOOLEAN)))
		.field(InputValue::new("notDistinctFrom", TypeRef::named(TypeRef::BOOLEAN)))
}

fn date_filter() -> InputObject {
	InputObject::new("DateFilter")
		.field(InputValue::new("equalTo", TypeRef::named("Date")))
		.field(InputValue::new("notEqualTo", TypeRef::named("Date")))
		.field(InputValue::new("isNull", TypeRef::named(TypeRef::BOOLEAN)))
		.field(InputValue::new("in", TypeRef::named_nn_list("Date")))
		.field(InputValue::new("notIn", TypeRef::named_nn_list("Date")))
		.field(InputValue::new("lessThan", TypeRef::named("Date")))
		.field(InputValue::new("lessThanOrEqualTo", TypeRef::named("Date")))
		.field(InputValue::new("greaterThan", TypeRef::named("Date")))
		.field(InputValue::new("greaterThanOrEqualTo", TypeRef::named("Date")))
		.field(InputValue::new("distinctFrom", TypeRef::named("Date")))
		.field(InputValue::new("notDistinctFrom", TypeRef::named("Date")))
}

fn datetime_filter() -> InputObject {
	InputObject::new("DatetimeFilter")
		.field(InputValue::new("equalTo", TypeRef::named("Datetime")))
		.field(InputValue::new("notEqualTo", TypeRef::named("Datetime")))
		.field(InputValue::new("isNull", TypeRef::named(TypeRef::BOOLEAN)))
		.field(InputValue::new("in", TypeRef::named_nn_list("Datetime")))
		.field(InputValue::new("notIn", TypeRef::named_nn_list("Datetime")))
		.field(InputValue::new("lessThan", TypeRef::named("Datetime")))
		.field(InputValue::new("lessThanOrEqualTo", TypeRef::named("Datetime")))
		.field(InputValue::new("greaterThan", TypeRef::named("Datetime")))
		.field(InputValue::new("greaterThanOrEqualTo", TypeRef::named("Datetime")))
		.field(InputValue::new("distinctFrom", TypeRef::named("Datetime")))
		.field(InputValue::new("notDistinctFrom", TypeRef::named("Datetime")))
}

fn json_filter() -> InputObject {
	InputObject::new("JSONFilter")
		.field(InputValue::new("equalTo", TypeRef::named("JSON")))
		.field(InputValue::new("notEqualTo", TypeRef::named("JSON")))
		.field(InputValue::new("isNull", TypeRef::named(TypeRef::BOOLEAN)))
		.field(InputValue::new("distinctFrom", TypeRef::named("JSON")))
		.field(InputValue::new("notDistinctFrom", TypeRef::named("JSON")))
}

/// Return the name of the scalar filter type for a given GraphQL type name.
pub fn filter_type_for(graphql_type: &str) -> &'static str {
	match graphql_type {
		"String" => "StringFilter",
		"Int" => "IntFilter",
		"BigInt" => "BigIntFilter",
		"Float" => "FloatFilter",
		"BigFloat" => "BigFloatFilter",
		"Boolean" => "BooleanFilter",
		"Date" => "DateFilter",
		"Datetime" => "DatetimeFilter",
		"JSON" => "JSONFilter",
		_ => "StringFilter", // fallback
	}
}
